### ISSUE TITLE
IndexError: max(): Expected reduction dim 0 to have non-zero size.

### ISSUE THREAD

**Issue by Lijp411** [ATR-DBI/CityRefer#12]
Hi, great work of this wonderful project! However, I'm having some problems in running cityrefer. I sincerely hope you can help me. 
I configured the environment of cityrefer as described in Installation, but I got an error when I ran the following command.
!pip install --upgrade git+https://gitclone.com//github.com/mit-han-lab/torchsparse.git@v1.4.0

###############################
Collecting git+https://gitclone.com//github.com/mit-han-lab/torchsparse.git@v1.4.0
  Cloning https://gitclone.com//github.com/mit-han-lab/torchsparse.git (to revision v1.4.0) to /tmp/pip-req-build-9mc56f1o
  Running command git clone --filter=blob:none --quiet https://gitclone.com//github.com/mit-han-lab/torchsparse.git /tmp/pip-req-build-9mc56f1o
  warning: filtering not recognized by server, ignoring
  Running command git checkout -q 74099d10a51c71c14318bce63d6421f698b24f24
  Resolved https://gitclone.com//github.com/mit-han-lab/torchsparse.git to commit 74099d10a51c71c14318bce63d6421f698b24f24
  Preparing metadata (setup.py) ... done
Building wheels for collected packages: torchsparse
  error: subprocess-exited-with-error
  
  × python setup.py bdist_wheel did not run successfully.
  │ exit code: 1
  ╰─> See above for output.
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  Building wheel for torchsparse (setup.py) ... error
  ERROR: Failed building wheel for torchsparse
  Running setup.py clean for torchsparse
Failed to build torchsparse
ERROR: Could not build wheels for torchsparse, which is required to install pyproject.toml-based projects
###############################

Then, I ran the following command to successfully install torch-sparse (but I'm not sure if the version is correct).
!python -c "$(curl -fsSL https://raw.githubusercontent.com/mit-han-lab/torchsparse/master/install.py)"

###############################
evaluate...
preparing data...
Loading data...
evaluating...
seed 42
generating the scores for seed 42...
  1% 2/225 [00:07<13:27,  3.62s/it]
Traceback (most recent call last):
  File "/content/gdrive/MyDrive/CityRefer-main/CityRefer-main/scripts/eval.py", line 444, in <module>
    eval_ref(args, CONF, DC)
  File "/content/gdrive/MyDrive/CityRefer-main/CityRefer-main/scripts/eval.py", line 194, in eval_ref
    data_dict = model(data_dict)
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/content/gdrive/MyDrive/CityRefer-main/CityRefer-main/models/cityrefer.py", line 108, in forward
    geo_feats = self.pooling(geo_feats)  
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "torchsparse/nn/modules/pooling.pyx", line 20, in torchsparse.nn.modules.pooling.GlobalMaxPool.forward
  File "torchsparse/nn/functional/pooling.pyx", line 25, in torchsparse.nn.functional.pooling.global_max_pool
IndexError: max(): Expected reduction dim 0 to have non-zero size.
###############################

**Comment by miyatai2** [comment]
The latter is an error reported on https://github.com/mit-han-lab/torchsparse/issues/218. 
This issue may come from the torchsparse version.

**Comment by Lijp411** [comment]
Would you mind telling me which verision of torchsparse did you use?
My specific version configuration is shown below.

##############
torchsparse                      2.1.0+torch113cu116
torch                            1.13.1+cu116
torchaudio                       0.13.1+cu116
torchdata                        0.7.0
torchsummary                     1.5.1
torchtext                        0.16.0
torchvision                      0.14.1+cu116
##############

**Comment by miyatai2** [comment]
I used torchsparse 1.4.0.
