### ISSUE TITLE
using checkpoint can’t reproduce the result

### ISSUE THREAD

**Issue by jmjff** [ATR-DBI/CityRefer#13]
Hello !
Thank you for your interesting work.
when I use the pre-trained model(xyz+color),the result is low.I am attaching the results for your consideration.
<img width="560" alt="image" src="https://github.com/ATR-DBI/CityRefer/assets/129597090/b157fb84-b103-491f-927a-af4ba7129e91">
That would be great if you can comment on the possible underlying issue here.
Many thanks for your time.
Regards.

**Comment by miyatai2** [comment]
Hi, it could be a seed problem, try about 5 times.

**Comment by jmjff** [comment]
Many thanks for reply! I have tried for over 5 times and the results keep same. So it may not be caused by the seed problem. By the way, when I run prepare_data.sh, I meet an error but it doesn't kill the process.

**Comment by jmjff** [comment]
Many thanks for your reply! I try more than 5 times but the results keep the same. So it may not be caused by the seed problem. By the way, I meet an error when I run prepare_data.sh. 
![image](https://github.com/ATR-DBI/CityRefer/assets/129597090/03fefd39-6aa3-449f-ba31-adcbc2d70520)
I wonder how can I solve the problem?

**Comment by miyatai2** [comment]
probably, you are using val data

**Comment by miyatai2** [comment]
probably you are using val data. 

I'll look into the error after tomorrow.
