### ISSUE TITLE
ScenesatUrban not available

### ISSUE THREAD

**Issue by ngailapdi** [ATR-DBI/CityRefer#17]
Just wondering if there is any link to download the point clouds handy. I tried to contact the authors of the ScenesatUrban paper but it seems like they have not responded to their github issues since 2022. Thank you for your help.

**Comment by miyatai2** [comment]
How about contacting them via email?

**Comment by ngailapdi** [comment]
I tried, no response either

**Comment by miyatai2** [comment]
Did you contact all the authors of the paper “Towards Semantic Segmentation of Urban-Scale 3D Point Clouds: A Dataset, Benchmarks and Challenges,” or just one of them?

**Comment by miyatai2** [comment]
@ngailapdi I found this repository [PushBoundary](https://github.com/shenglandu/PushBoundary) which includes a dataset link. I'm not sure whether this is official or not.

**Comment by Rabbia-Hassan** [comment]
I am facing the same problem. Any solution for this so far ?

**Comment by miyatai2** [comment]
@Rabbia-Hassan did you see the above link?

**Comment by Rabbia-Hassan** [comment]
yes, is that the official ScenesatUrban dataset? I mean is it the same as provided by the author ?

**Comment by miyatai2** [comment]
@Rabbia-Hassan Probably, the ply files are the same.
