### ISSUE TITLE
Coordinate System and Meta data for point cloud

### ISSUE THREAD

**Issue by navaaliqbal** [ATR-DBI/CityRefer#20]
Could you clarify the coordinate system and units for the coordinates in the .ply files of the dataset? I need this information to convert the XYZ coordinates to latitude and longitude for visualization in Google Earth Pro. kindly share the metadata for the point cloud, particularly any details about the coordinate system.

**Comment by miyatai2** [comment]
I asked the same question to the author of SensatUrban, but I did not receive a response. Thus, georeferencing was necessary to align the point cloud with the world map coordinates.

**Comment by navaaliqbal** [comment]
If possible, could you share the georeferenced dataset or provide guidance on how I might obtain it?

**Comment by miyatai2** [comment]
What data format would you prefer? Such dataset will be a subset of CityRefer  because it won’t be able to display cars or recently constructed or demolished buildings.

**Comment by navaaliqbal** [comment]
I need the geo referenced point clouds of the original sensatUrban point clouds in whichever format it is feasible for you to provide.
Please provide clarification if the geo referenced point clouds contain latitude, longitude, alt coordinates.

**Comment by miyatai2** [comment]
> I need the geo referenced point clouds of the original sensatUrban point clouds in whichever format it is feasible for you to provide. 

We cannot redistribute the point cloud data as we are not the authors of SensatUrban.

> Please provide clarification if the geo referenced point clouds contain latitude, longitude, alt coordinates.

We converted the geographical information from OpenStreetMap into a point cloud coordinate system. Point clouds that do not contain latitude, longitude, or altitude data were not transformed.

**Comment by navaaliqbal** [comment]
what do you mean exactly by the point cloud coordinate system ? Please provide more details on why you used OpenStreetMap in the process?

**Comment by miyatai2** [comment]
> what do you mean exactly by the point cloud coordinate system ?

The points in the dataset use absolute coordinates. Please check the point cloud data of SensatUrban.

> Please provide more details on why you used OpenStreetMap in the process?

Please see our paper.

**Comment by navaaliqbal** [comment]
Okay thanks, But using the procedure of georeferencing that you described in the paper, did you manage to convert the xyz coordinates into lat, long, alt format ?

**Comment by miyatai2** [comment]
We converted the latitude and longitude format into XY coordinates.

**Comment by navaaliqbal** [comment]
where did you get the latitude and longitude from because the original point cloud (SensatUrban) has x y z not coordinates and not lat, long, alt ?

**Comment by miyatai2** [comment]
We converted the latitude and longitude of OpenStreetMap information into XY coordinates.

**Comment by navaaliqbal** [comment]
How did you manage to get the 2d maps (through OpenStreetMap) of the point clouds accurately when there are no prominent landmarks in the point cloud? Given that the clouds contain information like roads, parking areas and houses/buildings, how did you find the exact locations on the 2D map?

**Comment by miyatai2** [comment]
City names are listed in the SensatUrban dataset. We find locations that corresponds to the point cloud.

**Comment by navaaliqbal** [comment]
I understand that the SensatUrban dataset contains point clouds for Birmingham and Cambridge, but upon examining some of the point clouds in CloudCompare, I found that they lack prominent landmarks or recognizable places that could easily correspond to those on OpenStreetMap.
Would it be possible for you to share the 2D maps (from OpenStreetMap) associated with all the point clouds? This would greatly assist in my efforts to georeference the data accurately.

**Comment by miyatai2** [comment]
Good luck!
https://www.dropbox.com/scl/fi/9evvifiec9c106alqs11n/osm_img.zip?rlkey=iau54ykdkzvl9uc8qry612po5&dl=0
