### ISSUE TITLE
coordShift.json

### ISSUE THREAD

**Issue by Chunmian-art** [ATR-DBI/CityRefer#4]
prepare_data.py needs balance_split/random-50_crop-250/train_250m/coordShift.json.
Could you provide it in your codebase?
Thank you!

**Comment by jmjff** [comment]
I meet the same problem

**Comment by miyatai2** [comment]
Please wait while I fix it.

**Comment by miyatai2** [comment]
done

**Comment by Rabbia-Hassan** [comment]
@Chunmian-art @jmjff  were you able to deal with this issue of  missing "coordShift.json" file  in the code?
